In [1]:
import numpy as np

In [2]:
# Question 1
print(np.version.version)

1.16.5


In [3]:
# Question 2
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [6]:
a[::-1]

array([4, 3, 2, 1, 0])

In [8]:
# Question 3
x=[1,2,3,4,5]
np.array(x)

array([1, 2, 3, 4, 5])

In [9]:
y=(1,2,3,4,5)
np.array(y)

array([1, 2, 3, 4, 5])

In [10]:
# Question 4
a=np.arange(5,10)
a

array([5, 6, 7, 8, 9])

In [19]:
b=np.arange(7,12)
b

array([ 7,  8,  9, 10, 11])

In [17]:
for i in a:
    if i in b:
        print(i,end=' ')

7 8 9 

In [23]:
# Question 5
a = np.array([100, 200, 300])
b = np.array([111, 121, 131])
  
print("Array a: ", a)
print("Array b: ", b)
  
print("a > b")
print(np.greater(a, b))
  
print("a >= b")
print(np.greater_equal(a, b))
  
print("a < b")
print(np.less(a, b))
  
print("a <= b")
print(np.less_equal(a, b))

Array a:  [100 200 300]
Array b:  [111 121 131]
a > b
[False  True  True]
a >= b
[False  True  True]
a < b
[ True False False]
a <= b
[ True False False]


In [24]:
# Question 6
z=np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
z.ndim

1

In [27]:
y=z.reshape(5,2)
y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
y.ndim

2

In [30]:
# Question 7
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
b=[]
for i in a:
    if i%3==0 or i%5==0:
        b.append(i)
print(b)

[0, 3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99]


In [37]:
from functools import  reduce
reduce(lambda x,y:x+y,b)

2318

In [42]:
# Question 8
a=np.arange(6).reshape(3,2)
a


array([[0, 1],
       [2, 3],
       [4, 5]])

In [45]:
list(a)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [46]:
# Question 9
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [48]:
b=np.arange(3).reshape(3,1)
b

array([[0],
       [1],
       [2]])

In [53]:
z=np.hstack((a,b))
z

array([[0, 1, 0],
       [2, 3, 1],
       [4, 5, 2]])

In [58]:
# Question 10
b=np.array([1,2,3])
b

array([1, 2, 3])

In [60]:
def arr(q):
    if len(q)==0:
        print("Numpy array is empty")
    else:
        print("Numpy array is not empty")
arr(b)  

Numpy array is not empty


In [61]:
arr(np.array([]))

Numpy array is empty


In [62]:
# Question 11

x= np.random.random((3,3))
print("Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("Normalized Array:")
print(x)


Array:
[[0.23281079 0.59531554 0.88685653]
 [0.4745168  0.60013855 0.88033127]
 [0.60271198 0.08333317 0.13565795]]
Normalized Array:
[[0.18602773 0.63717173 1.        ]
 [0.48683541 0.64317405 0.99187919]
 [0.64637674 0.         0.06511918]]


In [ ]:
# Question 12
np.seterr(all="ignore")

In [70]:
# Question 13
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [71]:
a[[0,2]]=a[[2,0]]
a

array([[4, 5],
       [2, 3],
       [0, 1]])

In [36]:
# Question 14

def samples(n):
    z=[]
    y=[]
    
    for i in range(n):
        i=np.random.randint(0, 10,(10))
        print(i)
        mean=i.mean()
        z.append(mean)
    print("Means are : ", z)
    m=max(z)
    for i in z:
        y.append(i/m*100)
    print("Percentiles are : ", y)

In [37]:
samples(10)

[4 9 9 6 6 2 0 6 0 1]
[2 0 1 1 7 4 9 0 7 0]
[8 8 3 9 8 2 1 8 9 9]
[0 7 7 9 3 0 1 4 6 0]
[8 7 7 9 2 3 1 6 5 1]
[5 3 7 2 1 0 9 8 2 4]
[3 7 7 6 7 4 6 0 8 7]
[4 0 4 1 2 4 2 9 9 7]
[0 8 2 7 4 5 4 8 8 8]
[2 8 9 8 9 6 0 3 2 0]
Means are :  [4.3, 3.1, 6.5, 3.7, 4.9, 4.1, 5.5, 4.2, 5.4, 4.7]
Percentiles are :  [66.15384615384615, 47.69230769230769, 100.0, 56.92307692307692, 75.3846153846154, 63.07692307692307, 84.61538461538461, 64.61538461538461, 83.07692307692308, 72.3076923076923]


In [76]:
# Question 15
x= np.random.random(10)
x

array([0.28089051, 0.07202376, 0.75447819, 0.54371827, 0.84913826,
       0.9897799 , 0.70035421, 0.58808073, 0.16879406, 0.31711197])

In [80]:
sorted(x)

[0.07202376293622614,
 0.16879406077837256,
 0.28089051473655535,
 0.3171119705525456,
 0.5437182707319718,
 0.5880807278936511,
 0.7003542093665045,
 0.7544781919817694,
 0.8491382624599078,
 0.9897798972735622]

In [81]:
# Question 16
a= np.random.random(10)
a

array([0.61080101, 0.52612336, 0.47492264, 0.18083209, 0.12344245,
       0.34865994, 0.31962819, 0.73618415, 0.95008785, 0.29590328])

In [82]:
b= np.random.random(10)
b

array([0.67855827, 0.71653214, 0.99629836, 0.77248162, 0.14178203,
       0.86946626, 0.04865428, 0.36306363, 0.99386321, 0.52017482])

In [83]:
a==b

array([False, False, False, False, False, False, False, False, False,
       False])

In [84]:
# Question 17
a+b

array([1.28935929, 1.2426555 , 1.471221  , 0.95331371, 0.26522448,
       1.2181262 , 0.36828247, 1.09924778, 1.94395106, 0.8160781 ])

In [85]:
a-b

array([-0.06775726, -0.19040877, -0.52137572, -0.59164953, -0.01833958,
       -0.52080632,  0.2709739 ,  0.37312052, -0.04377536, -0.22427154])

In [86]:
a/b

array([0.90014526, 0.73426345, 0.47668716, 0.23409242, 0.87064949,
       0.40100457, 6.56937387, 2.02770008, 0.95595434, 0.56885352])

In [87]:
a*b

array([0.41446408, 0.3769843 , 0.47316465, 0.13968947, 0.01750192,
       0.30314805, 0.01555128, 0.26728169, 0.94425736, 0.15392144])

In [90]:
# Question 18

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yesterday:  2021-04-15
Today:  2021-04-16
Tomorrow:  2021-04-17
